import { Champ } from '../interfaces/champs.interface';

export const CHAMPS: Champ[] = [
    { name: 'Fernando Alonso', imageUrl: '../../../../assets/drivers-1000x400/alonso.png', imageUrlSmall: '../../../../assets/drivers-500x400/alonso.png', description: 'Fernando Alonso Díaz je španielsky pilot Formuly 1, dvojnásobný majster sveta z rokov 2005 a 2006. Okrem toho zvíťazil 2x na pretekoch 24-Le Mans a k získaniu tzv Triple Crown of Motosport mu chýba iba víťazstvo z Indianapolis 500.' },
    { name: 'Mario Andretti', imageUrl: '../../../../assets/drivers-1000x400/andretti.png', imageUrlSmall: '../../../../assets/drivers-500x400/andretti.png', description: 'Mario Gabriele Andretti je bývalý taliansko-americký jazdec formuly 1 a majster sveta z roku 1978. V roku 1984 získal aj titul v seriáli CART. V roku 2005 bol uvedený do Automobilovej siene slávy.'  },
    { name: 'Alberto Ascari', imageUrl: '../../../../assets/drivers-1000x400/ascari.png', imageUrlSmall: '../../../../assets/drivers-500x400/ascari.png', description: 'Alberto Ascari bol taliansky pilot Formuly 1, dvojnásobný majster sveta z rokov 1952 a 1953. Pôsobil v tímoch Ferrari, pre ktorý získal 2 tituly, Maserati a Lancia. Jeho život ukončila 26. mája 1955 nehoda, keď pri testovaní v Monze vyletel mimo trať a dvakrát sa prevrátil.'  },
    { name: 'Jack Brabham', imageUrl: '../../../../assets/drivers-1000x400/brabham.png', imageUrlSmall: '../../../../assets/drivers-500x400/brabham.png', description: 'Sir John Arthur "Jack" Brabham bol austrálsky automobilový pretekár a jazdec Formuly 1. Trikrát sa stal majstrom sveta, v rokoch 1959, 1960 a 1966. Bol tiež zakladateľom rovnomennej pretekárskej stajne Brabham. Zomrel v roku 2014 ako najstarší žijúci majster sveta formuly 1.'  },
    { name: 'Jenson Button', imageUrl: '../../../../assets/drivers-1000x400/button.png', imageUrlSmall: '../../../../assets/drivers-500x400/button.png', description: 'Jenson Alexander Lyons Button je britský pilot F1, ktorý v roku 2009 vyhral svetový šampionát za tím Brawn GP. Po kariére vo Formule 1 sa stal v roku 2018 spolu-šampiónom série Super GT, v ktorej zdieľal auto Honda s Naoki Yamamotom v tíme Kunimitsu.'  },

    { name: 'Jim Clark', imageUrl: '../../../../assets/drivers-1000x400/clark.png', imageUrlSmall: '../../../../assets/drivers-500x400/clark.png', description: 'James Clark OBE bol britský pretekár zo Škótska, ktorý v rokoch 1963 a 1965 získal dva tituly majstra sveta formuly 1. Bol všestranným jazdcom, v roku 1965 vyhral Indianapolis 500. Bol spojený najmä s tímom Lotus, za ktorý jazdil celú svoju kariéru vo Formule 1 v rokoch 1960 až 1968.'  },
    { name: 'Juan Manuel Fangio', imageUrl: '../../../../assets/drivers-1000x400/fangio.png', imageUrlSmall: '../../../../assets/drivers-500x400/fangio.png', description: 'Juan Manuel Fangio bol argentínsky automobilový pretekár, účastník majstrovstiev sveta formuly 1. Získal 5 majstrovských titulov, z toho 4 v rade za sebou. Išlo o rekord, ktorý bol vyrovnaný až v roku 2002 Michaelom Schumacherom. Dňa 17. júla 1995 vo veku 84 rokov podľahol srdcovému kolapsu.'  },
    { name: 'Emilio Giuseppe Farina', imageUrl: '../../../../assets/drivers-1000x400/farina.png', imageUrlSmall: '../../../../assets/drivers-500x400/farina.png', description: 'Emilio Giuseppe Farina, prezývaný aj Nino, bol taliansky automobilový pretekár a prvý majster sveta Formuly 1 z roku 1950 za tím Alfa Romeo. Je iróniou osudu, že Farina, ktorý počas svojej pretekárskej kariéry prežil množstvo ťažkých nehôd, zahynul nakoniec pri automobilovej nehode počas cesty na Veľkú cenu Francúzska 1966.'  },
    { name: 'Emerson Fittipaldi', imageUrl: '../../../../assets/drivers-1000x400/fittipaldi.png', imageUrlSmall: '../../../../assets/drivers-500x400/fittipaldi.png', description: 'Emerson Fittipaldi je bývalý brazílsky automobilový pretekár, ktorý dvakrát vyhral majstrovstvá sveta Formuly 1 a Indianapolis 500 a raz šampionát CART. V roku 2005 sa Fittipaldi prekvapujúco vrátil do súťažných pretekov na podujatí Grand Prix Masters, ktoré sa konalo v Kyalami v Južnej Afrike, a skončil druhý za kolegom z F1 Nigelom Mansellom.'  },
    { name: 'Graham Hill', imageUrl: '../../../../assets/drivers-1000x400/grahamHill.png', imageUrlSmall: '../../../../assets/drivers-500x400/grahamHill.png', description: 'Norman Graham Hill OBE bol britský pretekár a majiteľ tímu, ktorý sa stal dvakrát majstrom sveta formuly 1. V rokoch 1962 a 1968 zvíťazil a trikrát obsadil druhé miesto (1963, 1964 a 1965). Napriek tomu, že Hill zložil vodičské skúšky až v roku 1953, keď mal už 24 rokov, a do sveta motoristického športu vstúpil až o rok neskôr, stal sa jedným z najlepších jazdcov svojej generácie.'  },

    { name: 'Mika Häkkinen', imageUrl: '../../../../assets/drivers-1000x400/hakkinen.png', imageUrlSmall: '../../../../assets/drivers-500x400/hakkinen.png', description: 'Mika Pauli Häkkinen je bývalý fínsky automobilový pretekár a dvojnásobný majster sveta vo Formule 1. V rokoch 1991 až 2001 pretekal vo Formule 1, v prvých dvoch sezónach za tím Lotus, neskôr za McLaren. V rokoch 1998 a 1999 sa stal majstrom sveta. 20 víťazstiev v 161 pretekoch. Prezývaný je „lietajúci Fín“.'  },
    { name: 'Lewis Hamilton', imageUrl: '../../../../assets/drivers-1000x400/hamilton.png', imageUrlSmall: '../../../../assets/drivers-500x400/hamilton.png', description: 'Sir Lewis Carl Davidson Hamilton je britský automobilový pretekár súťažiaci vo Formule 1, jazdiaci za Mercedes. Hamilton získal spolu s Michaelom Schumacherom rekordných sedem titulov majstra sveta jazdcov formuly 1 a okrem iného je držiteľom rekordov v počte víťazstiev (104), pole position (104) a pódiových umiestnení (199).'  },
    { name: 'Mike Hawthorn', imageUrl: '../../../../assets/drivers-1000x400/Hawthorn.png', imageUrlSmall: '../../../../assets/drivers-500x400/Hawthorn.png', description: 'John Michael Hawthorn bol britský pretekár. V roku 1958 sa stal prvým britským jazdcom majstrom sveta formuly 1. Potom oznámil svoj odchod do dôchodku, pretože ho hlboko zasiahla smrť jeho tímového kolegu a priateľa Petra Collinsa, ku ktorej došlo dva mesiace predtým počas Veľkej ceny Nemecka 1958. Tri mesiace po odchode do dôchodku zomrel pri dopravnej nehode.'  },
    { name: 'Damon Hill', imageUrl: '../../../../assets/drivers-1000x400/hill.png', imageUrlSmall: '../../../../assets/drivers-500x400/hill.png', description: 'Damon Graham Devereux Hill, je bývalý britský profesionálny pretekár z Anglicka a majster sveta formuly 1 z roku 1996. Je synom Grahama Hilla a spolu s Nicom Rosbergom je jedným z dvoch synov majstra sveta formuly 1, ktorí tiež získali titul. V roku 1981 začal pretekať na motocykloch a po menších úspechoch prešiel na preteky jednomiestnych automobilov.'  },
    { name: 'Denny Hulme', imageUrl: '../../../../assets/drivers-1000x400/hulme.png', imageUrlSmall: '../../../../assets/drivers-500x400/hulme.png', description: 'Denis Clive Hulme bol novozélandský pretekár, ktorý v roku 1967 vyhral majstrovstvá sveta jazdcov formuly 1 za tím Brabham. Od svojho debutu v Monaku v roku 1965 až po posledné preteky Veľkej ceny USA 1974 štartoval na 112 Veľkých cenách, čoho výsledkom bolo osem víťazstiev a 33 pódiových umiestnení. V rokoch 1968 a 1972 skončil tretí aj v celkovom poradí.'  },

    { name: 'James Hunt', imageUrl: '../../../../assets/drivers-1000x400/hunt.png', imageUrlSmall: '../../../../assets/drivers-500x400/hunt.png', description: 'James Simon Wallis Hunt bol britský pretekár, ktorý v roku 1976 vyhral majstrovstvá sveta formuly 1. Po ukončení pretekárskej kariéry v roku 1979 sa Hunt stal mediálnym komentátorom a podnikateľom až do svojej smrti. Známy bol aj svojou rivalitou s Nikim Laudom.'  },
    { name: 'Alan Jones', imageUrl: '../../../../assets/drivers-1000x400/jones.png', imageUrlSmall: '../../../../assets/drivers-500x400/jones.png', description: 'Alan Stanley Jones je bývalý austrálsky jazdec formuly 1. Bol prvým jazdcom, ktorý s tímom Williams vyhral majstrovstvá sveta formuly 1. V roku 1980 sa stal majstrom sveta jazdcov a po trojnásobnom majstrovi sveta Sirovi Jackovi Brabhamovi bol druhým Austrálčanom, ktorému sa to podarilo. Celkovo sa zúčastnil 117 Veľkých cien, z ktorých vyhral 12 a dosiahol 24 pódiových umiestnení.'  },
    { name: 'Keke Rosberg', imageUrl: '../../../../assets/drivers-1000x400/kekeRosberg.png', imageUrlSmall: '../../../../assets/drivers-500x400/kekeRosberg.png', description: 'Keijo Erik Rosberg, známy ako "Keke", je bývalý fínsky pretekár a víťaz majstrovstiev sveta formuly 1 z roku 1982. Bol prvým fínskym jazdcom, ktorý vyhral šampionát. Je otcom Nica Rosberga, majstra sveta formuly 1 z roku 2016. Do roku 2008 riadil aj svojho syna Nica, ktorý vstúpil do formuly 1 v roku 2006 a jazdil za tím Williams F1.'  },
    { name: 'Niki Lauda', imageUrl: '../../../../assets/drivers-1000x400/lauda.png', imageUrlSmall: '../../../../assets/drivers-500x400/lauda.png', description: 'Andreas Nikolaus „Niki“ Lauda bol rakúsky pilot Formuly 1, trojnásobný majster sveta z rokov 1975, 1977 a 1984. Dva roky bol tiež manažérom pretekárskeho tímu Jaguar Formula One. Pred úmrtím pracoval ako odborný konzultant pre nemecké televízie počas Veľkých cien a fungoval ako nevýkonný predseda pre tím Mercedes AMG Petronas F1.'  },
    { name: 'Nigel Mansell', imageUrl: '../../../../assets/drivers-1000x400/mansell.png', imageUrlSmall: '../../../../assets/drivers-500x400/mansell.png', description: 'Nigel Ernest James Mansell je britský automobilový pretekár, ktorý vyhral majstrovstvá sveta formuly 1 (1992) a svetovú sériu CART Indy Car (1993). Mansell bol úradujúcim šampiónom F1, keď prešiel do CART a stal sa prvým človekom, ktorý získal titul CART vo svojej debutovej sezóne, a stal sa jediným človekom, ktorý súčasne získal titul F1 a Indie.'  },

    { name: 'Phil Hill', imageUrl: '../../../../assets/drivers-1000x400/phillHill.png', imageUrlSmall: '../../../../assets/drivers-500x400/phillHill.png', description: 'Philip Toll Hill Jr. bol americký pretekár. Bol jedným z dvoch amerických jazdcov, ktorí vyhrali majstrovstvá sveta jazdcov formuly 1, a jediným, ktorý sa narodil v Spojených štátoch. Získal aj tri víťazstvá v pretekoch športových automobilov 24 hodín Le Mans a 12 hodín Sebringu. Hilla opisovali ako "rozvážneho, jemného muža".'  },
    { name: 'Nelson Piquet', imageUrl: '../../../../assets/drivers-1000x400/piquet.png', imageUrlSmall: '../../../../assets/drivers-500x400/piquet.png', description: 'Nelson Piquet Souto Maior je brazílsky pretekár a podnikateľ na dôchodku, ktorý trikrát vyhral majstrovstvá sveta jazdcov v rokoch 1981, 1983 a 1987. Od júla 2022 má Piquet zakázaný vstup do paddocku F1 za rasistické a homofóbne vyjadrenia.'  },
    { name: 'Alain Prost', imageUrl: '../../../../assets/drivers-1000x400/prost.png', imageUrlSmall: '../../../../assets/drivers-500x400/prost.png', description: 'Alain Prost  je bývalý francúzsky automobilový pretekár a štvornásobný majster sveta Formuly 1. Iba Juan Manuel Fangio (5), Lewis Hamilton (7) a Michael Schumacher (7) majú na svojom konte viac majstrovských titulov ako Prost. V rokoch 1987 až 2001 držal Prost titul pre najviac víťazstiev Grand Prix.'  },
    { name: 'Kimi Räikkönen', imageUrl: '../../../../assets/drivers-1000x400/raikkonen.png', imageUrlSmall: '../../../../assets/drivers-500x400/raikkonen.png', description: 'Kimi-Matias Räikkönen prezývaný „Ice Man“ je bývalý fínsky pilot formuly 1, ktorý naposledy jazdil za tím Alfa Romeo Racing (bývalý tím Sauber). V roku 2007 získal s tímom Scuderia Ferrari titul majstra sveta. V súčasnosti (2024) je zatiaľ posledný šampión tímu Ferrari.'  },
    { name: 'Jochen Rindt', imageUrl: '../../../../assets/drivers-1000x400/rindt.png', imageUrlSmall: '../../../../assets/drivers-500x400/rindt.png', description: 'Karl Jochen Rindt bol pretekár narodený v Nemecku, ktorý väčšinu svojho života strávil v Rakúsku a súťažil ako Rakúšan. V roku 1970 sa zabil počas tréningu na Veľkú cenu Talianska a stal sa jediným jazdcom, ktorý posmrtne získal titul majstra sveta jazdcov formuly 1.'  },

    { name: 'Nico Rosberg', imageUrl: '../../../../assets/drivers-1000x400/rosberg.png', imageUrlSmall: '../../../../assets/drivers-500x400/rosberg.png', description: 'Nico Rosberg je bývalý nemecký pilot Formuly 1. V rokoch 2006 – 2009 jazdil za stajňu Williams, no v roku 2010 prestúpil do tímu Mercedes, v ktorom pôsobil do roku 2016, kedy získal svoj jediný titul majstra sveta a rozhodol sa ukončiť profesionálnu kariéru. Pretekal za Nemecko, ale v skoršej dobe reprezentoval Fínsko, vlasť svojho otca, keďže má štátnu príslušnosť oboch štátov.'  },
    { name: 'Jody Scheckter', imageUrl: '../../../../assets/drivers-1000x400/scheckter.png', imageUrlSmall: '../../../../assets/drivers-500x400/scheckter.png', description: 'Jody David Scheckter je juhoafrický podnikateľ a automobilový pretekár na dôchodku. Vo Formule 1 súťažil v rokoch 1972 až 1980, pričom v roku 1979 vyhral s Ferrari majstrovstvá sveta jazdcov. Scheckter je prvým a do roku 2024 jediným jazdcom z afrického kontinentu, ktorý vyhral preteky Formuly 1 alebo majstrovstvá sveta jazdcov.'  },
    { name: 'Michael Schumacher', imageUrl: '../../../../assets/drivers-1000x400/schumacher.png', imageUrlSmall: '../../../../assets/drivers-500x400/schumacher.png', description: 'Michael Schumacher je bývalý nemecký pretekár, ktorý súťažil vo Formule 1 za tímy Jordan, Benetton, Ferrari a Mercedes. Schumacher má na svojom konte rekordných sedem titulov majstra sveta v pretekoch automobilov (spolu s Lewisom Hamiltonom). V decembri 2013 utrpel Schumacher pri nehode na lyžiach vážne poranenie mozgu.'  },
    { name: 'Ayrton Senna', imageUrl: '../../../../assets/drivers-1000x400/senna.png', imageUrlSmall: '../../../../assets/drivers-500x400/senna.png', description: 'Ayrton Senna da Silva bol brazílsky pretekár, ktorý vyhral majstrovstvá sveta jazdcov formuly 1 v rokoch 1988, 1990 a 1991. Senna, jeden z troch brazílskych jazdcov formuly 1, ktorí sa stali majstrami sveta. Zomrel v dôsledku nehody, keď viedol Veľkú cenu San Marína 1994, jazdiac za tím Williams.'  },
    { name: 'Jackie Stewart', imageUrl: '../../../../assets/drivers-1000x400/stewart.png', imageUrlSmall: '../../../../assets/drivers-500x400/stewart.png', description: 'Sir John Young Stewart je bývalý britský pretekár formuly 1 zo Škótska. Vo Formule 1 súťažil v rokoch 1965 až 1973, pričom počas týchto deviatich sezón vyhral tri tituly majstra sveta a dvakrát skončil na druhom mieste. Až do Lewisa Hamiltona v roku 2015 bol jediným britským jazdcom, ktorý vyhral tri šampionáty.'  },

    { name: 'John Surtees', imageUrl: '../../../../assets/drivers-1000x400/surtees.png', imageUrlSmall: '../../../../assets/drivers-500x400/surtees.png', description: 'John Norman Surtees bol britský motocyklový pretekár Veľkej ceny a jazdec Formuly 1. Na ceste za titulom sedemnásobného majstra sveta v pretekoch Grand Prix motocyklov získal svoj prvý titul v roku 1956 a následne v rokoch 1958 až 1960 získal tri po sebe idúce double, čím získal šesť titulov majstra sveta v triedach 500 a 350 cm3.'  },
    { name: 'Max Verstappen', imageUrl: '../../../../assets/drivers-1000x400/verstappen.png', imageUrlSmall: '../../../../assets/drivers-500x400/verstappen.png', description: 'Max Emilian Verstappen je belgický a holandský pretekár, ktorý súťaží vo Formule 1 pod holandskou vlajkou za tím Red Bull Racing. Verstappen získal tri tituly majstra sveta jazdcov formuly 1, ktoré s tímom Red Bull získal postupne v rokoch 2021 až 2023. Verstappen je synom bývalého jazdca formuly 1 Josa Verstappena a bývalej motokárovej pretekárky Sophie Kumpenovej.'  },
    { name: 'Sebastian Vettel', imageUrl: '../../../../assets/drivers-1000x400/vettel.png', imageUrlSmall: '../../../../assets/drivers-500x400/vettel.png', description: 'Sebastian Vettel je bývalý nemecký pilot Formuly 1, ktorý pretekal za stajňu Aston Martin. V roku 2010 získal titul majstra sveta za stajňu Red Bull Racing, ktorý následne obhájil i v rokoch 2010, 2011, 2012 a 2013. Patrí medzi najúspešnejších pilotov F1 všetkých čias. Je jedným z piatich jazdcov, ktorí majú na konte štyri alebo viac titulov majstra sveta.'  },
    { name: 'Jacques Villeneuve', imageUrl: '../../../../assets/drivers-1000x400/villeneuve.png', imageUrlSmall: '../../../../assets/drivers-500x400/villeneuve.png', description: 'Jacques Villeneuve je bývalý kanadský profesionálny pretekár a amatérsky hudobník, ktorý v roku 1997 vyhral s Williamsom majstrovstvá sveta formuly 1. Okrem Formuly 1 súťažil aj v rôznych iných formách automobilových pretekov, pričom v roku 1995 vyhral preteky Indianapolis 500 a v roku 1995 PPG Indy Car World Series. '  }
  ];